#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

#get colors from .Xresources
get_xcolor(){
	xresources=$(\
		cat ~/.Xresources\
	)
	color=$(\
		echo $xresources | \
		sed "s/.*\*color$1: \(#[0-9A-Fa-f]*\).*/\1/"\
	)
	echo $color
}

#Wallpaper
WALLPAPER=/home/tom/Pictures/rocks.jpg

#Numix color palette
LIGHT=$(get_xcolor 15)
LLIGHT=$(get_xcolor 7)
ACCENT=$(get_xcolor 12)
LDARK=$(get_xcolor 8)
DARK=$(get_xcolor 0)

#Panel and padding
padding=20
monitor_width=$(hc list_monitors | sed 's/^[0-9]: \([0-9]*\)x.*$/\1/')
panel_height=24
panel_width=$(echo "$monitor_width - (2 * $padding)" | bc)

hc emir_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn xterm
hc keybind $Mod-grave spawn dmenu_run -h $panel_height -w $panel_width -x $padding -y $padding -p "Run:" -nb $DARK -nf $LIGHT -sb $ACCENT -sf $DARK
hc keybind XF86AudioLowerVolume spawn amixer set Master 5%-
hc keybind XF86AudioRaiseVolume spawn amixer set Master 5%+

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( I II III IV V VI VII VIII IX X )
tag_keys=( {1..9} 0 )

# Selecting workspaces
hc keybind Alt-Control-Left 	use_index -1
hc keybind Alt-Control-Right 	use_index +1
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc set focus_follows_mouse 1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $LDARK
hc set frame_border_normal_color $DARK
hc set frame_bg_normal_color $LDARK
hc set frame_bg_active_color $DARK
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color $ACCENT
hc attr theme.normal.color $DARK
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color $DARK
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color $DARk
hc attr theme.active.inner_color $DARK
hc attr theme.active.outer_color $DARK
hc attr theme.background_color $DARK

hc set window_gap $padding
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

#Start panel in all monitors
start_panel() {
	for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
		"$1" $monitor $panel_height $padding $LIGHT $LLIGHT $ACCENT $LDARK $DARK $2&
	done
}

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
if pgrep panel.sh >> /dev/null
then
	kill $(pgrep panel.sh)
	start_panel $panel
else
	start_panel $panel
fi

#Wallpaper
feh --bg-fill $WALLPAPER

#Start compton if not running
start_compton(){ compton -c -z & }
if pgrep compton >> /dev/null
then
	kill $(pgrep compton)
	start_compton
else
	start_compton
fi

#Load .Xresources
xrdb -load ~/.Xresources

#Start pulseaudio
if pgrep pulseaudio >> /dev/null
then
	kill $(pgrep pulseaudio)
	pulseaudio --start
else
	pulseaudio --start
fi

#Start xscreensaver
if pgrep xscreensaver >> /dev/null
then
	kill $(pgrep xscreensaver)
	xscreensaver -no-splash&
else
	xscreensaver -no-splash&
fi
