#!/usr/bin/env bash

declare -A colors
colors=(["background"]="#2d2d2d" ["foreground"]="#f9f9f9"
        ["color0"]="#2d2d2d"     ["color8"]="#333333"
        ["color1"]="#690a03"     ["color9"]="#d64937"
        ["color2"]="#13a43b"     ["color10"]="#6dfb2d"
        ["color3"]="#f5a711"     ["color11"]="#ffdc00"
        ["color4"]="#0f6cc9"     ["color12"]="#32abd8"
        ["color5"]="#93116b"     ["color13"]="#c61f93"
        ["color6"]="#3cb691"     ["color14"]="#53b4bd"
        ["color7"]="#d9d9d9"     ["color15"]="#f9f9f9")

# Wallpaper
export HLWM_WALLPAPER="$HOME/.config/herbstluftwm/wallpapers/poligons.png"

# Shadow
export HLWM_COMPOSITING=true

# Padding
export HLWM_WINDOW_PADDING=20

# Panel
export HLWM_PANEL_HEIGHT=25
export HLWM_PANEL_FONT="DejaVu Sans Mono-10"

# Colors
export HLWM_FG_COLOR=${colors["color15"]}
export HLWM_ACCENT_COLOR=${colors["color5"]}
export HLWM_BG_COLOR=${colors["color0"]}
