#!/usr/bin/env bash

# this is a simple config for herbstluftwm

# The current directory
dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Herbstclient shortcut
hc() {
    herbstclient "$@"
}

#Include the theming script
source "$dir/theme"

#Detect monitors
hc set auto_detect_monitors 1
hc detect_monitors

#Panel and window_p
monitor_w=($(hc list_monitors | sed 's/^[0-9]: \([0-9]*\)x.*$/\1/'))
panel_w=$(echo "$monitor_w - (2 * $window_p)" | bc)
dmenu_opts="-h $panel_h -w $panel_w -x $window_p -y $window_p -p Run: -nb $color_bg -nf $color_fg -sb $color_accent -sf $color_bg"

# Tags
tag_names=()
tag_keys=({1..9} 0)
for key in ${tag_keys[@]}; do
	if [ $key -eq 0 ]; then key=10; fi
	key=$(echo "$key - 1" | bc)
	echo $key
	name=$(echo "obase=2;$key" | bc | awk '{ printf "%04d", $0 }')
	tag_names+=($name)
done;

# Source hlwm-config-files
source "$dir/hlwm-keybindings"
source "$dir/hlwm-theming"
source "$dir/hlwm-rules"

# Unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# Start panel in all monitors
start_panel() {
	for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
		"$1" $monitor&
	done
}

# Find the panel
panel=$dir/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
if pgrep panel.sh >> /dev/null
then
	kill $(pgrep panel.sh)
	start_panel $panel
else
	start_panel $panel
fi

pulseaudio --start

$dir/start.sh "xautolock -time 5 -locker $dir/lock.sh"
$dir/start.sh "feh --bg-fill $wallpaper"
$dir/start.sh "compton --config $HOME/.compton"
$dir/start.sh "xrdb -load $HOME/.Xresources"
$dir/start.sh "xset +fp /usr/share/fonts/local"
$dir/start.sh "xset fp rehash"
#$dir/start.sh "$dir/notify.sh $dir/popup.sh"
