#!/usr/bin/env bash

# Remove all existing keybindings
hc keyunbind --all

# Keybindings
Mod=Mod4   # Use the super key as the main modifier


hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r chain , spawn echo "!! HLWM reload config !!" , reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn xterm
hc keybind $Mod-Alt-l spawn xautolock -locknow

hc keybind $Mod-Escape spawn rofi -color-enabled -modi "run,ssh" -show run
hc keybind $Mod-a spawn rofi -color-enabled -modi "drun" -show drun
hc keybind $Mod-t spawn env HLWM_CONF_DIR=$HLWM_CONF_DIR $HLWM_CONF_DIR/rofi_theme.sh -color-enabled

hc keybind XF86AudioMute spawn amixer set Master toggle
hc keybind XF86AudioLowerVolume spawn amixer set Master 1%-
hc keybind XF86AudioRaiseVolume spawn amixer set Master 1%+

hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5

hc keybind XF86AudioPlay spawn playerctl play-pause

# Basic movement
# Focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# Moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# Splitting frames
# Create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# Let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# Resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# Selecting workspaces
hc keybind Alt-Control-h 	use_index -1
hc keybind Alt-Control-l 	use_index +1
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# Layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# Mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc set focus_follows_mouse 1
