#!/usr/bin/env bash

# Theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_normal_opacity 0
hc set frame_active_opacity 0
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color $color_accent
hc attr theme.normal.color $color_bg
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color $color_bg
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color $color_bg
hc attr theme.active.inner_color $color_bg
hc attr theme.active.outer_color $color_bg
hc attr theme.background_color $color_bg

hc set window_gap $window_p
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 1
